### ISSUE TITLE
AttributeError: module 'lzss' has no attribute 'encode'

### ISSUE THREAD

**Issue by 21-ko** [yyogo/pylzss#10]
Error message
```
Traceback (most recent call last):
  File "C:\Users\user1\Desktop\lzss\test.py", line 15, in <module>
    compress_file(input_filename, output_filename)
  File "C:\Users\user1\Desktop\lzss\test.py", line 7, in compress_file
    compressed_data = lzss.encode(data)
                      ^^^^^^^^^^^
AttributeError: module 'lzss' has no attribute 'encode'
```

Examples used
```
import lzss

def compress_file(input_file, output_file):
    with open(input_file, 'rb') as file:
        data = file.read()

    compressed_data = lzss.encode(data)

    with open(output_file, 'wb') as file:
        file.write(compressed_data)

input_filename = 'test.txt'
output_filename = 'test.bin'

compress_file(input_filename, output_filename)
```

Problem I'm having: Module is not working.

**Comment by 21-ko** [comment]
Just saw issue 5. Finally solved this problem.
https://github.com/yyogo/pylzss/issues/5

**Comment by 21-ko** [comment]
[pylzss.zip](https://github.com/yyogo/pylzss/files/13756705/pylzss.zip)
After fixing the problem, if you installed the module through setup, do pip uninstall lzss.
